DROP TABLE IF EXISTS task;
CREATE TABLE task (
  `ID` BIGINT AUTO_INCREMENT NOT NULL,
  `TITLE` VARCHAR(45) NOT NULL,
  `CONTENT` VARCHAR(45) NOT NULL,
  `WRITER` VARCHAR(45) NOT NULL,
  `DELETED` BOOLEAN NOT NULL,
  `PREVIOUS_ID` VARCHAR(45) NULL,
  `TASK_TYPE` VARCHAR(45) NOT NULL,
  `IS_HEAD` BOOLEAN NOT NULL,
  PRIMARY KEY (`ID`)
);
