-- MySQL Script generated by MySQL Workbench
-- Thu Apr  8 21:30:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo` DEFAULT CHARACTER SET utf8;
USE `todo`;

-- -----------------------------------------------------
-- Table `todo`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`User`;

CREATE TABLE IF NOT EXISTS `todo`.`User`
(
    `Id`       INT         NOT NULL AUTO_INCREMENT,
    `UserId`   VARCHAR(45) NOT NULL,
    `Password` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`Id`),
    UNIQUE INDEX `UserId_UNIQUE` (`UserId` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`ColumnType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`ColumnType`;

CREATE TABLE IF NOT EXISTS `todo`.`ColumnType`
(
    `id`   INT         NOT NULL,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`Card`;

CREATE TABLE IF NOT EXISTS `todo`.`Card`
(
    `Id`         INT         NOT NULL,
    `Owner`      INT         NOT NULL,
    `Title`      VARCHAR(45) NOT NULL,
    `Content`    VARCHAR(45) NOT NULL,
    `Priority`   DOUBLE      NOT NULL,
    `ColumnType` INT         NOT NULL,
    PRIMARY KEY (`Id`),
    INDEX `fk_Card_User_idx` (`Owner` ASC),
    INDEX `fk_Card_Status1_idx` (`ColumnType` ASC),
    CONSTRAINT `fk_Card_User`
        FOREIGN KEY (`Owner`)
            REFERENCES `todo`.`User` (`Id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_Card_Status1`
        FOREIGN KEY (`ColumnType`)
            REFERENCES `todo`.`ColumnType` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`ActionType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`ActionType`;

CREATE TABLE IF NOT EXISTS `todo`.`ActionType`
(
    `Id`   INT         NOT NULL,
    `Name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`Id`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`History`;

CREATE TABLE IF NOT EXISTS `todo`.`History`
(
    `Id`     INT      NOT NULL,
    `Card`   INT      NOT NULL,
    `Action` INT      NOT NULL,
    `Date`   DATETIME NOT NULL,
    `From`   INT      NULL,
    `To`     INT      NULL,
    PRIMARY KEY (`Id`),
    INDEX `fk_History_Card1_idx` (`Card` ASC),
    INDEX `fk_History_ColumnType1_idx` (`From` ASC),
    INDEX `fk_History_ColumnType2_idx` (`To` ASC),
    INDEX `fk_History_Action1_idx` (`Action` ASC),
    CONSTRAINT `fk_History_Card1`
        FOREIGN KEY (`Card`)
            REFERENCES `todo`.`Card` (`Id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_History_ColumnType1`
        FOREIGN KEY (`From`)
            REFERENCES `todo`.`ColumnType` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_History_ColumnType2`
        FOREIGN KEY (`To`)
            REFERENCES `todo`.`ColumnType` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_History_Action1`
        FOREIGN KEY (`Action`)
            REFERENCES `todo`.`ActionType` (`Id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
