-- MySQL Script generated by MySQL Workbench
-- Thu Apr  8 23:05:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo` DEFAULT CHARACTER SET utf8;
USE `todo`;

-- -----------------------------------------------------
-- Table `todo`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`user`;

CREATE TABLE IF NOT EXISTS `todo`.`user`
(
    `ID`       INT         NOT NULL AUTO_INCREMENT,
    `USER_ID`  VARCHAR(45) NOT NULL,
    `PASSWORD` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `UserId_UNIQUE` (`USER_ID` ASC)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`column_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`column_type`;

CREATE TABLE IF NOT EXISTS `todo`.`column_type`
(
    `ID`   INT         NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`card`;

CREATE TABLE IF NOT EXISTS `todo`.`card`
(
    `ID`       INT         NOT NULL AUTO_INCREMENT,
    `OWNER`    INT         NOT NULL,
    `TITLE`    VARCHAR(45) NOT NULL,
    `CONTENT`  VARCHAR(45) NOT NULL,
    `PRIORITY` DOUBLE      NOT NULL,
    `COLUMN`   INT         NOT NULL,
    `DELETED`  TINYINT     NULL,
    PRIMARY KEY (`ID`),
    INDEX `fk_Card_User_idx` (`OWNER` ASC),
    INDEX `fk_Card_Status1_idx` (`COLUMN` ASC),
    CONSTRAINT `fk_Card_User`
        FOREIGN KEY (`OWNER`)
            REFERENCES `todo`.`user` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE CASCADE,
    CONSTRAINT `fk_Card_Status1`
        FOREIGN KEY (`COLUMN`)
            REFERENCES `todo`.`column_type` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`action_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`action_type`;

CREATE TABLE IF NOT EXISTS `todo`.`action_type`
(
    `ID`   INT         NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo`.`history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `todo`.`history`;

CREATE TABLE IF NOT EXISTS `todo`.`history`
(
    `ID`      INT      NOT NULL AUTO_INCREMENT,
    `CARD`    INT      NOT NULL,
    `ACTION`  INT      NOT NULL,
    `DATE`    DATETIME NOT NULL,
    `FROM`    INT      NULL,
    `TO`      INT      NULL,
    `DELETED` TINYINT  NULL,
    PRIMARY KEY (`ID`),
    INDEX `fk_History_Card1_idx` (`CARD` ASC),
    INDEX `fk_History_ColumnType1_idx` (`FROM` ASC),
    INDEX `fk_History_ColumnType2_idx` (`TO` ASC),
    INDEX `fk_History_Action1_idx` (`ACTION` ASC),
    CONSTRAINT `fk_History_Card1`
        FOREIGN KEY (`CARD`)
            REFERENCES `todo`.`card` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE CASCADE,
    CONSTRAINT `fk_History_ColumnType1`
        FOREIGN KEY (`FROM`)
            REFERENCES `todo`.`column_type` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE CASCADE,
    CONSTRAINT `fk_History_ColumnType2`
        FOREIGN KEY (`TO`)
            REFERENCES `todo`.`column_type` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE CASCADE,
    CONSTRAINT `fk_History_Action1`
        FOREIGN KEY (`ACTION`)
            REFERENCES `todo`.`action_type` (`ID`)
            ON DELETE NO ACTION
            ON UPDATE CASCADE
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
