INSERT INTO CARD (ID, TITLE, CONTENTS, DATE_TIME, TODO, DOING, DONE, DELETED) VALUES (1, 'TEST1', 'TESTCONTENTS1', CURRENT_TIMESTAMP(), TRUE, FALSE, FALSE, FALSE);
INSERT INTO CARD (ID, TITLE, CONTENTS, DATE_TIME, TODO, DOING, DONE, DELETED) VALUES (2, 'TEST2', 'TESTCONTENTS2', CURRENT_TIMESTAMP(), FALSE, TRUE, FALSE, FALSE);
INSERT INTO CARD (ID, TITLE, CONTENTS, DATE_TIME, TODO, DOING, DONE, DELETED) VALUES (3, 'TEST3', 'TESTCONTENTS3', CURRENT_TIMESTAMP(), FALSE, FALSE, TRUE, FALSE);
INSERT INTO CARD (ID, TITLE, CONTENTS, DATE_TIME, TODO, DOING, DONE, DELETED) VALUES (4, 'TEST4', 'TESTCONTENTS4', CURRENT_TIMESTAMP(), FALSE, FALSE, FALSE, TRUE);
