INSERT INTO CARD (ID, TITLE, CONTENTS, DATE_TIME, STATUS, DELETED) VALUES (1, 'TEST1', 'TESTCONTENTS1', CURRENT_TIMESTAMP(), 0, FALSE);
INSERT INTO CARD (ID, TITLE, CONTENTS, DATE_TIME, STATUS, DELETED) VALUES (2, 'TEST2', 'TESTCONTENTS2', CURRENT_TIMESTAMP(),1, FALSE);
INSERT INTO CARD (ID, TITLE, CONTENTS, DATE_TIME, STATUS, DELETED) VALUES (3, 'TEST3', 'TESTCONTENTS3', CURRENT_TIMESTAMP(), 2, FALSE);
INSERT INTO CARD (ID, TITLE, CONTENTS, DATE_TIME, STATUS, DELETED) VALUES (4, 'TEST4', 'TESTCONTENTS4', CURRENT_TIMESTAMP(), 0, TRUE);
