INSERT INTO CARD (ID, TITLE, CONTENTS, DATE_TIME, STATUS) VALUES (1, 'TEST1', 'TESTCONTENTS1', CURRENT_TIMESTAMP(), 0);
INSERT INTO CARD (ID, TITLE, CONTENTS, DATE_TIME, STATUS) VALUES (2, 'TEST2', 'TESTCONTENTS2', CURRENT_TIMESTAMP(), 1);
INSERT INTO CARD (ID, TITLE, CONTENTS, DATE_TIME, STATUS) VALUES (3, 'TEST3', 'TESTCONTENTS3', CURRENT_TIMESTAMP(), 2);
INSERT INTO CARD (ID, TITLE, CONTENTS, DATE_TIME, STATUS) VALUES (4, 'TEST4', 'TESTCONTENTS4', CURRENT_TIMESTAMP(), 3);
