INSERT INTO COLUMNS (NAME, PROJECT, PROJECT_key) VALUES ('TODO', 1, 0);
INSERT INTO COLUMNS (NAME, PROJECT, PROJECT_key) VALUES ('PROGRESS', 1, 1);
INSERT INTO COLUMNS (NAME, PROJECT, PROJECT_key) VALUES ('DONE', 1, 2);
